services:
  # PostgreSQL Database
  - type: pserv
    name: internship-db
    env: python
    plan: free
    
  # Django Backend
  - type: web
    name: internship-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: internship-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: False
