# Generated by Django 4.2.7 on 2026-04-20 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title/heading', max_length=200)),
                ('message', models.TextField(help_text='Notification message body')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('ADVISOR_ASSIGNED', 'Advisor Assigned'), ('ADVISOR_ASSIGNMENT_NEEDED', 'Advisor Assignment Needed'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('REPORT_SUBMITTED', 'Monthly Report Submitted'), ('INTERNSHIP_COMPLETED', 'Internship Completed'), ('GENERAL', 'General Notification')], db_index=True, default='GENERAL', help_text='Type of notification', max_length=50)),
                ('link', models.CharField(blank=True, help_text='Direct link to relevant page (e.g., /student/internships/123)', max_length=500, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (internship, application, etc.)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., internship, application)', max_length=50, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
