# Generated by Django 4.2.7 on 2026-04-20 06:08

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('STUDENT', 'Student'), ('COMPANY', 'Company'), ('ADVISOR', 'Advisor'), ('DEPARTMENT', 'Department Head')], db_index=True, max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('document', models.FileField(help_text='Required document (PDF, max 5MB)', upload_to='uploads/registrations/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('student_dob', models.DateField(blank=True, null=True)),
                ('student_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('student_university_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_skills', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('company_contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('advisor_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('advisor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('advisor_staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_head_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='departments.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Request',
                'verbose_name_plural': 'Registration Requests',
                'db_table': 'registration_requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['email'], name='registratio_email_b0b6d2_idx'), models.Index(fields=['status'], name='registratio_status_ac51a3_idx'), models.Index(fields=['request_type'], name='registratio_request_bbec50_idx')],
            },
        ),
    ]
