# Generated by Django 6.0.4 on 2026-04-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='target_departments',
            field=models.ManyToManyField(blank=True, help_text='Multiple departments (used for Companies)', related_name='multi_registration_requests', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department (used for Students/Advisors)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='departments.department'),
        ),
    ]
