# Generated by Django 6.0.4 on 2026-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registrationrequest_target_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='student_batch',
            field=models.CharField(blank=True, help_text='Student batch/cohort', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='student_year_of_study',
            field=models.IntegerField(blank=True, help_text='Year of study (1-5)', null=True),
        ),
    ]
