# Generated by Django 6.0.4 on 2026-05-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registrationrequest_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='advising_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
