# Generated by Django 6.0.4 on 2026-04-21 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the recipient has read this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor_assignment', models.ForeignKey(help_text='The advisor assignment this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisors.advisorassignment')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['advisor_assignment', 'created_at'], name='messages_advisor_530958_idx'), models.Index(fields=['sender', 'is_read'], name='messages_sender__bb2957_idx')],
            },
        ),
    ]
