# Generated by Django 4.2.7 on 2026-04-20 06:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('verification_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('student_name', models.CharField(max_length=255)),
                ('student_university_id', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('internship_title', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('advisor_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('performance_grade', models.CharField(blank=True, max_length=5)),
                ('dept_head_name', models.CharField(blank=True, default='', help_text='Department head full name at time of issue (from Department.head_name)', max_length=255)),
                ('company_rep_name', models.CharField(blank=True, default='', help_text='Company contact person name (from CompanyProfile.contact_person_name)', max_length=255)),
                ('company_rep_title', models.CharField(blank=True, default='', help_text='Company contact person title (from CompanyProfile.contact_person_title)', max_length=100)),
                ('uil_director_name', models.CharField(blank=True, default='', help_text='UIL director name at time of issue (from settings.UIL_DIRECTOR_NAME)', max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='reports.finalreport')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['certificate_id'], name='certificate_certifi_a0a669_idx'), models.Index(fields=['verification_code'], name='cert_vcode_idx'), models.Index(fields=['student'], name='certificate_student_e19697_idx')],
            },
        ),
    ]
