# Generated by Django 6.0.4 on 2026-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo snapshot at time of issue', null=True, upload_to='certificates/company_logos/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='company_seal',
            field=models.ImageField(blank=True, help_text='Company seal snapshot at time of issue', null=True, upload_to='certificates/company_seals/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='company_signature',
            field=models.ImageField(blank=True, help_text='Company representative signature snapshot at time of issue', null=True, upload_to='certificates/company_signatures/'),
        ),
    ]
