# Generated by Django 4.2.7 on 2026-04-20 06:08

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('UIL', 'UIL'), ('DEPARTMENT_HEAD', 'Department Head'), ('ADVISOR', 'Advisor'), ('STUDENT', 'Student'), ('COMPANY', 'Company')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by UIL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department (null for Admin and UIL roles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advisor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('staff_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('document', models.FileField(help_text='University staff ID card or appointment letter (PDF, max 5MB)', upload_to='uploads/advisors/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advisor Profile',
                'verbose_name_plural': 'Advisor Profiles',
                'db_table': 'advisor_profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Short company description')),
                ('document', models.FileField(help_text='Company commercial license or official letter (PDF, max 5MB)', upload_to='uploads/companies/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentHeadProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='department_head_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document', models.FileField(help_text='Official department approval letter (PDF, max 5MB)', upload_to='uploads/departments/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Head Profile',
                'verbose_name_plural': 'Department Head Profiles',
                'db_table': 'department_head_profiles',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('university_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('skills', models.TextField(help_text='Comma-separated skills (used for internship recommendations)')),
                ('document', models.FileField(help_text='University acceptance letter or student ID card (PDF, max 5MB)', upload_to='uploads/students/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['university_id'], name='student_pro_univers_262da4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_approved'], name='users_is_appr_73f710_idx'),
        ),
    ]
