# Generated by Django 6.0.4 on 2026-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG/PNG)', null=True, upload_to='uploads/avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Past roles, projects, or work experience'),
        ),
    ]
