# Generated by Django 6.0.4 on 2026-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_avatar_studentprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Professional summary/bio'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Profile cover banner (JPG/PNG)', null=True, upload_to='uploads/banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education',
            field=models.TextField(blank=True, help_text='University, degree, and graduation year'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='Professional headline (e.g., Software Engineering Student)', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=100),
        ),
    ]
