# Generated by Django 6.0.4 on 2026-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_about_studentprofile_banner_and_more'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='target_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this company recruits from', related_name='company_profiles', to='departments.department'),
        ),
    ]
