# Generated by Django 6.0.4 on 2026-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companyprofile_target_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='max_students',
            field=models.IntegerField(default=15, help_text='Maximum number of students this advisor is allowed to supervise'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='If true, this company is blocked from further internships in specific departments'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='eligibility_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_eligible',
            field=models.BooleanField(default=False, help_text='Validated by Department Head for the current internship cycle'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(default=4, help_text='Current year of study (e.g. 4 for final year, 5 for Architecture/Medicine)'),
        ),
    ]
