# Generated by Django 6.0.4 on 2026-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_advisorprofile_max_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentheadprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentheadprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
