# Generated by Django 6.0.4 on 2026-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_departmentheadprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='certificate_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of company representative (PNG with transparency)', null=True, upload_to='uploads/company_signatures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo for certificates (PNG/JPG, recommended: 500x500px)', null=True, upload_to='uploads/company_logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_seal',
            field=models.ImageField(blank=True, help_text='Official company seal/stamp for certificates (PNG with transparency recommended)', null=True, upload_to='uploads/company_seals/%Y/%m/'),
        ),
    ]
