# Generated by Django 6.0.4 on 2026-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companyprofile_certificate_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certificates',
            field=models.TextField(blank=True, help_text='Certifications, awards, and achievements'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='Personal or academic projects with descriptions'),
        ),
    ]
