# Generated by Django 6.0.4 on 2026-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentprofile_certificates_studentprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, help_text='Student batch/cohort (e.g., "2024", "Batch A 2024", "Fall 2024")', max_length=50, null=True),
        ),
    ]
