# Generated by Django 6.0.4 on 2026-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
