# Generated by Django 6.0.4 on 2026-05-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='advising_location',
            field=models.TextField(blank=True, help_text='Preferred location for advising students (e.g., Office Building A, Room 205)', null=True),
        ),
    ]
