# Generated by Django 6.0.4 on 2026-05-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_advisorprofile_advising_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_location_1',
            field=models.CharField(blank=True, help_text='First choice location for internship (e.g., Addis Ababa, Dire Dawa)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_location_2',
            field=models.CharField(blank=True, help_text='Second choice location for internship', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_location_3',
            field=models.CharField(blank=True, help_text='Third choice location for internship', max_length=100, null=True),
        ),
    ]
