# Generated by Django 6.0.4 on 2026-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentprofile_preferred_location_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_location_1',
            field=models.CharField(default='Addis Ababa', help_text='First choice location for internship (e.g., Addis Ababa, Dire Dawa) - REQUIRED', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_location_2',
            field=models.CharField(default='Dire Dawa', help_text='Second choice location for internship - REQUIRED', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_location_3',
            field=models.CharField(default='Bahir Dar', help_text='Third choice location for internship - REQUIRED', max_length=100),
        ),
    ]
