# Generated by Django 6.0.4 on 2026-05-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_studentprofile_preferred_location_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='supervisor_email',
            field=models.EmailField(blank=True, help_text='Email address of the supervisor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Name of the supervisor overseeing interns', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='supervisor_phone',
            field=models.CharField(blank=True, help_text='Phone number of the supervisor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='supervisor_title',
            field=models.CharField(blank=True, help_text='Job title of the supervisor', max_length=100, null=True),
        ),
    ]
