# Generated by Django 6.0.4 on 2026-05-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_supervisor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='supervisor_email',
            field=models.EmailField(blank=True, default='', help_text='Email address of the supervisor (Required for active internships)', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='supervisor_name',
            field=models.CharField(blank=True, default='', help_text='Name of the supervisor overseeing interns (Required for active internships)', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='supervisor_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of the supervisor (Required for active internships)', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='supervisor_title',
            field=models.CharField(blank=True, default='', help_text='Job title of the supervisor (Required for active internships)', max_length=100),
        ),
    ]
