# Generated by Django 4.2.7 on 2026-04-20 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/position name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the internship role and responsibilities')),
                ('required_skills', models.TextField(help_text='Comma-separated skills required (used for recommendation engine)')),
                ('location', models.CharField(help_text='City or address where internship takes place', max_length=200)),
                ('duration_months', models.IntegerField(help_text='Internship duration in months (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField(help_text='Internship start date')),
                ('end_date', models.DateField(blank=True, help_text='Internship end date (calculated or manual)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this internship is currently visible')),
                ('max_applicants', models.IntegerField(default=5, help_text='Maximum number of students that can be accepted', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('application_deadline', models.DateField(blank=True, help_text='Last date to accept applications (optional)', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Applications'), ('CLOSED', 'Closed'), ('FILLED', 'All Positions Filled')], db_index=True, default='OPEN', help_text='Current status of internship posting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company posting this internship', limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_internships', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department this internship belongs to (inherited from company)', on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='departments.department')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'db_table': 'internships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='internships_company_ff89c2_idx'), models.Index(fields=['department', 'status'], name='internships_departm_1842b0_idx'), models.Index(fields=['status', 'is_active'], name='internships_status_1fa7c5_idx'), models.Index(fields=['start_date'], name='internships_start_d_f38597_idx'), models.Index(fields=['created_at'], name='internships_created_1a1271_idx')],
            },
        ),
    ]
