# Generated by Django 6.0.4 on 2026-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Optional company logo for this internship posting', null=True, upload_to='internship_logos/'),
        ),
    ]
