# Generated by Django 4.2.7 on 2026-04-20 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter from student', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current status of application', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='When student applied')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship', models.ForeignKey(help_text='Internship being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Company user who reviewed this application', limit_choices_to={'role': 'COMPANY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who applied', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='application_student_a8a36b_idx'), models.Index(fields=['internship', 'status'], name='application_interns_c406d5_idx'), models.Index(fields=['status'], name='application_status_e61111_idx'), models.Index(fields=['-applied_at'], name='application_applied_f50165_idx')],
                'unique_together': {('student', 'internship')},
            },
        ),
    ]
