# Generated by Django 6.0.4 on 2026-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted (Placed)'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current status of application', max_length=10),
        ),
    ]
