# Generated by Django 6.0.4 on 2026-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='about_me',
            field=models.TextField(blank=True, help_text='Professional summary/bio for this specific application', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, help_text='Relevant certificate or supporting document (PDF/Image)', null=True, upload_to='uploads/applications/certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, help_text='Current education level (e.g., Bachelor, Master)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True, help_text='Past roles and work experience relevant to this internship', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='projects',
            field=models.TextField(blank=True, help_text='Previous projects or relevant work', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Optional additional cover letter from student', null=True),
        ),
    ]
