# Generated by Django 6.0.4 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_about_me_application_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, help_text='Current education level (e.g., Bachelor, Master)', max_length=500, null=True),
        ),
    ]
