# Generated by Django 4.2.7 on 2026-04-20 06:08

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.IntegerField(help_text='Month number (1 = first month, 2 = second month, etc.)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('attendance_rate', models.DecimalField(decimal_places=2, help_text='Attendance percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tasks_completed', models.TextField(help_text='Description of tasks completed during this month')),
                ('performance_rating', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], help_text='Overall performance rating for the month', max_length=20)),
                ('comments', models.TextField(help_text='Additional comments and feedback from company')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Auto-generated PDF report', null=True, upload_to='reports/monthly/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_assignment', models.ForeignKey(help_text='Advisor assignment this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='advisors.advisorassignment')),
                ('company', models.ForeignKey(help_text='Company submitting the report', limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student this report is about', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='Company user who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'db_table': 'monthly_reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student'], name='monthly_rep_student_4a1f58_idx'), models.Index(fields=['advisor_assignment'], name='monthly_rep_advisor_85fc2f_idx'), models.Index(fields=['submitted_at'], name='monthly_rep_submitt_31f7e9_idx')],
                'unique_together': {('student', 'advisor_assignment', 'report_month')},
            },
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_ADVISOR', 'Pending Advisor'), ('SUBMITTED_TO_DEPARTMENT', 'Submitted to Department'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING_ADVISOR', help_text='Current status of the report', max_length=30)),
                ('internship_duration', models.CharField(help_text='Duration of internship (e.g., "3 months")', max_length=100)),
                ('company_performance_assessment', models.TextField(help_text='Company assessment of student performance')),
                ('skills_developed', models.TextField(help_text='Skills student developed during internship')),
                ('key_achievements', models.TextField(help_text='Key achievements and accomplishments')),
                ('company_recommendation', models.CharField(choices=[('YES', 'Yes - Recommend'), ('NO', 'No - Do Not Recommend'), ('CONDITIONAL', 'Conditional')], help_text='Company recommendation for future employment', max_length=15)),
                ('company_comments', models.TextField(help_text='Additional comments from company')),
                ('company_submitted_at', models.DateTimeField(blank=True, help_text='When company submitted their section', null=True)),
                ('advisor_evaluation', models.TextField(blank=True, help_text='Advisor overall evaluation', null=True)),
                ('academic_integration', models.TextField(blank=True, help_text='Assessment of academic integration', null=True)),
                ('professional_development', models.TextField(blank=True, help_text='Professional development observations', null=True)),
                ('improvement_areas', models.TextField(blank=True, help_text='Areas for improvement', null=True)),
                ('overall_grade', models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('F', 'F - Fail')], help_text='Overall grade assigned by advisor', max_length=1, null=True)),
                ('advisor_submitted_at', models.DateTimeField(blank=True, help_text='When advisor submitted their section', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Auto-generated complete report PDF', null=True, upload_to='reports/final/%Y/%m/', validators=[core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(help_text='Advisor completing the report', limit_choices_to={'role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='completed_final_reports', to=settings.AUTH_USER_MODEL)),
                ('advisor_assignment', models.OneToOneField(help_text='Advisor assignment this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='advisors.advisorassignment')),
                ('company', models.ForeignKey(help_text='Company submitting the report', limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_final_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student this report is about', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Final Report',
                'verbose_name_plural': 'Final Reports',
                'db_table': 'final_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='final_repor_student_16d061_idx'), models.Index(fields=['advisor_assignment'], name='final_repor_advisor_85dfcf_idx'), models.Index(fields=['status'], name='final_repor_status_c6548d_idx')],
            },
        ),
    ]
