# Generated by Django 6.0.4 on 2026-04-21 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.IntegerField(help_text='Month number (1 = first month, 2 = second month, etc.)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tasks_performed', models.TextField(help_text='Description of tasks performed during this month')),
                ('skills_learned', models.TextField(help_text='Skills and knowledge acquired during this month')),
                ('challenges_faced', models.TextField(help_text='Challenges or issues encountered')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_assignment', models.ForeignKey(help_text='Advisor assignment this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_monthly_reports', to='advisors.advisorassignment')),
                ('student', models.ForeignKey(help_text='Student submitting this report', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_personal_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Monthly Report',
                'verbose_name_plural': 'Student Monthly Reports',
                'db_table': 'student_monthly_reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student'], name='student_mon_student_56248b_idx'), models.Index(fields=['advisor_assignment'], name='student_mon_advisor_bd6fed_idx'), models.Index(fields=['submitted_at'], name='student_mon_submitt_77f16e_idx')],
                'unique_together': {('student', 'advisor_assignment', 'report_month')},
            },
        ),
    ]
