# Generated by Django 6.0.4 on 2026-04-21 17:37

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
        ('reports', '0002_studentmonthlyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Final Evaluation', 'verbose_name_plural': 'Final Evaluations'},
        ),
        migrations.RemoveField(
            model_name='finalreport',
            name='academic_integration',
        ),
        migrations.RemoveField(
            model_name='finalreport',
            name='company_comments',
        ),
        migrations.RemoveField(
            model_name='finalreport',
            name='improvement_areas',
        ),
        migrations.RemoveField(
            model_name='finalreport',
            name='key_achievements',
        ),
        migrations.RemoveField(
            model_name='finalreport',
            name='professional_development',
        ),
        migrations.RemoveField(
            model_name='finalreport',
            name='skills_developed',
        ),
        migrations.AddField(
            model_name='finalreport',
            name='advisor_score',
            field=models.IntegerField(default=0, help_text='Advisor evaluation score (0-100), contributes 50%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='company_score',
            field=models.IntegerField(default=0, help_text='Company evaluation score (0-100), contributes 50%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='criteria_scores',
            field=models.JSONField(default=dict, help_text='Structured scores for evaluation criteria'),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='total_score',
            field=models.FloatField(default=0.0, help_text='Combined weighted score (Company 50% + Advisor 50%)'),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='advisor_evaluation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='advisor_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='company',
            field=models.ForeignKey(help_text='Company submitting the report', limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_final_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='company_performance_assessment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='company_recommendation',
            field=models.CharField(choices=[('YES', 'Yes - Recommend'), ('NO', 'No - Do Not Recommend'), ('CONDITIONAL', 'Conditional')], max_length=15),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='company_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='internship_duration',
            field=models.CharField(help_text='Duration of internship', max_length=100),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='overall_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (90-100)'), ('B', 'B (80-89)'), ('C', 'C (70-79)'), ('D', 'D (60-69)'), ('F', 'F (<60)')], help_text='Final Letter Grade', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/final/%Y/%m/', validators=[core.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='status',
            field=models.CharField(choices=[('PENDING_ADVISOR', 'Pending Advisor Review'), ('SUBMITTED_TO_DEPARTMENT', 'Submitted to Department'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING_ADVISOR', help_text='Current status of the report', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentFinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(help_text='The final report document (PDF)', upload_to='reports/student_final/%Y/', validators=[core.validators.validate_pdf_file])),
                ('summary', models.TextField(help_text='Brief summary of internship achievements')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REVISIONS_REQUIRED', 'Revisions Required')], default='PENDING', max_length=20)),
                ('advisor_feedback', models.TextField(blank=True, help_text='Feedback from advisor for revisions', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_final_report', to='advisors.advisorassignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_final_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_final_reports',
            },
        ),
    ]
