# Generated by Django 6.0.4 on 2026-04-22 10:46

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_finalreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmonthlyreport',
            name='hours_worked',
            field=models.IntegerField(blank=True, help_text='Total hours worked this month', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='studentmonthlyreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='Supplemental documentation (PDF/DOC)', null=True, upload_to='reports/student_monthly/%Y/%m/', validators=[core.validators.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='studentmonthlyreport',
            name='solutions_applied',
            field=models.TextField(blank=True, help_text='How the challenges were resolved', null=True),
        ),
    ]
