# Generated by Django 6.0.4 on 2026-04-22 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_studentmonthlyreport_hours_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='problem_solving_score',
            field=models.IntegerField(default=0, help_text='Problem Solving score (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='professionalism_score',
            field=models.IntegerField(default=0, help_text='Professionalism score (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='skill_development_score',
            field=models.IntegerField(default=0, help_text='Skill Development score (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='task_completion_score',
            field=models.IntegerField(default=0, help_text='Task Completion score (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
