# Generated by Django 6.0.4 on 2026-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_monthlyreport_problem_solving_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='avg_monthly_score',
            field=models.FloatField(default=0.0, help_text='Average score of all monthly reports (contributes 40%)'),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='total_score',
            field=models.FloatField(default=0.0, help_text='Combined weighted score (Monthly 40% + Company 30% + Advisor 30%)'),
        ),
    ]
