# Generated by Django 6.0.4 on 2026-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_finalreport_avg_monthly_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='department_review',
            field=models.TextField(blank=True, help_text='Academic performance review and final comments from Department Head', null=True),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='department_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
