# Generated by Django 6.0.4 on 2026-04-23 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_finalreport_department_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='certificate_issued',
            field=models.BooleanField(default=False, help_text='Whether certificate has been generated and issued to student'),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='certificate_issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued the certificate (Department Head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='department_approved',
            field=models.BooleanField(default=False, help_text='Whether the Department Head has approved this report for certificate generation'),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='Department Head who reviewed this report', limit_choices_to={'role': 'DEPARTMENT_HEAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_final_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='status',
            field=models.CharField(choices=[('PENDING_ADVISOR', 'Pending Advisor Review'), ('SUBMITTED_TO_DEPARTMENT', 'Submitted to Department Head'), ('APPROVED_BY_DEPARTMENT', 'Approved by Department Head'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING_ADVISOR', help_text='Current status of the report', max_length=30),
        ),
    ]
