# Generated by Django 6.0.4 on 2026-04-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('FAILING_STUDENT', 'Student Performance Risk'), ('INACTIVE_ADVISOR', 'Advisor Inactivity'), ('COMPANY_ISSUE', 'Company Policy Violation'), ('PLACEMENT_CONFLICT', 'Placement Conflict'), ('OTHER', 'Other Strategic Issue')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open (Awaiting Resolution)'), ('RESOLVED', 'Resolved'), ('ESCALATED_TO_UIL', 'Escalated to UIL')], default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_escalations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_escalations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_escalations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='departments.department')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='e.g., 2026')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active cycle?')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='departments.department')),
            ],
            options={
                'db_table': 'department_cycles',
                'unique_together': {('department', 'year', 'semester')},
            },
        ),
    ]
