# Generated by Django 4.2.7 on 2026-04-20 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this assignment is currently active')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the internship was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(help_text='Advisor supervising the student', limit_choices_to={'role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_students', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(blank=True, help_text='Original application (optional link)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignment', to='applications.application')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment (UIL or Department Head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_advisor_assignments', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(help_text='Internship being supervised', on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='internships.internship')),
                ('student', models.ForeignKey(help_text='Student being supervised', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_advisor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisor Assignment',
                'verbose_name_plural': 'Advisor Assignments',
                'db_table': 'advisor_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Feedback content from advisor to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_assignment', models.ForeignKey(help_text='Advisor assignment this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='advisors.advisorassignment')),
                ('created_by', models.ForeignKey(help_text='Advisor who created this feedback', limit_choices_to={'role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['advisor_assignment'], name='feedbacks_advisor_63796e_idx'), models.Index(fields=['created_at'], name='feedbacks_created_1c526e_idx'), models.Index(fields=['created_by'], name='feedbacks_created_b3001e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='advisorassignment',
            index=models.Index(fields=['student', 'is_active'], name='advisor_ass_student_f1de3f_idx'),
        ),
        migrations.AddIndex(
            model_name='advisorassignment',
            index=models.Index(fields=['advisor', 'is_active'], name='advisor_ass_advisor_016574_idx'),
        ),
        migrations.AddIndex(
            model_name='advisorassignment',
            index=models.Index(fields=['internship'], name='advisor_ass_interns_fb2bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='advisorassignment',
            index=models.Index(fields=['application'], name='advisor_ass_applica_a2d00b_idx'),
        ),
        migrations.AddConstraint(
            model_name='advisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('application',), name='unique_active_advisor_per_application'),
        ),
    ]
